# Generated by Django 4.1.2 on 2025-03-12 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="StudentAttendance",
        ),
    ]
