# Generated by Django 4.1.2 on 2025-03-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0004_auto_20201124_0614"),
        ("attendance", "0003_class_student_attendance"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Class",
            new_name="SchoolClass",
        ),
        migrations.AlterField(
            model_name="student",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_students",
                to="corecode.studentclass",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="current_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_in_class",
                to="corecode.studentclass",
            ),
        ),
    ]
