# Generated by Django 4.1.2 on 2025-03-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("corecode", "0004_auto_20201124_0614"),
        ("attendance", "0004_rename_class_schoolclass_alter_student_class_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SchoolClass",
        ),
        migrations.DeleteModel(
            name="StudentBulkUpload",
        ),
        migrations.RemoveField(
            model_name="student",
            name="class_id",
        ),
        migrations.AddField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="corecode.studentclass",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Leave", "Leave"),
                ],
                default="Absent",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="attendance.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="address",
            field=models.TextField(verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="attendance_status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                default="Absent",
                max_length=10,
                verbose_name="Attendance Status",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="current_class",
            field=models.CharField(max_length=50, verbose_name="Current Class"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="fullname",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="parent_number",
            field=models.CharField(
                max_length=15, verbose_name="Parent's Contact Number"
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="registration_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Registration Number"
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="section",
            field=models.CharField(max_length=10, verbose_name="Section"),
        ),
    ]
