# Generated by Django 4.1.2 on 2025-03-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0022_alter_student_options_and_more"),
        ("attendance", "0005_delete_schoolclass_delete_studentbulkupload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="students.student",
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
