# Generated by Django 4.1.2 on 2025-03-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0024_alter_student_father_mobile_number"),
        ("finance", "0002_class_student_fee_alter_invoice_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fee",
            name="student",
        ),
        migrations.RemoveField(
            model_name="student",
            name="class_name",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="Fee",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
